// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH3Q0uGkZjvl2feRweHl1UtRfZmMbORIA',
    appId: '1:191063471850:web:7eb8bd47b5cf9109dac993',
    messagingSenderId: '191063471850',
    projectId: 'buy-it-c05dc',
    authDomain: 'buy-it-c05dc.firebaseapp.com',
    storageBucket: 'buy-it-c05dc.appspot.com',
    measurementId: 'G-WTJJKNY0NS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbLozMrRbK1i0fqhO8nm4Ov0sCUk-J5b4',
    appId: '1:191063471850:android:f219d31226022081dac993',
    messagingSenderId: '191063471850',
    projectId: 'buy-it-c05dc',
    storageBucket: 'buy-it-c05dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhEqa5lvRDEmOF2K9Lg8b9rpxS0hqI930',
    appId: '1:191063471850:ios:833ad05604c85e82dac993',
    messagingSenderId: '191063471850',
    projectId: 'buy-it-c05dc',
    storageBucket: 'buy-it-c05dc.appspot.com',
    iosClientId: '191063471850-hmjd2f5ii2vcrip9vm2h75fvkim622s0.apps.googleusercontent.com',
    iosBundleId: 'com.example.fl3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhEqa5lvRDEmOF2K9Lg8b9rpxS0hqI930',
    appId: '1:191063471850:ios:957f77ef6f3a22dddac993',
    messagingSenderId: '191063471850',
    projectId: 'buy-it-c05dc',
    storageBucket: 'buy-it-c05dc.appspot.com',
    iosClientId: '191063471850-6m2b68tpg6cqo20l5n6n92o6u3rch00e.apps.googleusercontent.com',
    iosBundleId: 'com.example.fl3.RunnerTests',
  );
}
